<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType> <!-- Użyj 'Library' dla bibliotek DLL, 'WinExe' dla aplikacji okienkowych -->
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Tutaj przenieś tylko zaktualizowane paczki NuGet -->
    <PackageReference Include="opendnp3" Version="3.1.2" />
  </ItemGroup>
</Project>